### ISSUE TITLE
Usage message param count differs from behaviour

### ISSUE THREAD

**Issue by dznz** [flaviusb/pineapplepizza-rust-reference#3]
Third parameter seems to be optional, and to default to printing to stdout. However, if only the first two parameters are included, usage string is printed. Looks like off-by-one at `main.rs#231`.

**Comment by flaviusb** [comment]
I have tried
```
cargo run examples/self.🍍🍕 --html
cargo run examples/self.🍍🍕 --json
cargo run examples/self.🍍🍕 --rust-debug
```
and all seem to correctly print to stdout. https://github.com/flaviusb/pineapplepizza-rust-reference/blob/master/src/main.rs#L231 checks for `args.len() < 3` because args[0] is the name of the executable; in the previous examples, it is "target/debug/pineapplepizza".

Can you replicate this on HEAD with the above commands?

**Comment by dznz** [comment]
```sh
    Finished dev [unoptimized + debuginfo] target(s) in 0.70s
     Running `target/debug/pineapplepizza 'examples/self.🍍🍕' --json`
thread 'main' panicked at 'No header found.', src/main.rs:191:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I've been doing it via this but the result is the same

```sh
 $ ./target/debug/pineapplepizza examples/self.🍍🍕 --json
thread 'main' panicked at 'No header found.', src/main.rs:191:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

versions:

```sh
cargo 1.51.0 (43b129a20 2021-03-16)
rustc 1.51.0 (2fd73fabe 2021-03-23)
```

I'm running the whole thing in a container, for what that's worth

```sh
$ uname -a
Linux b3cdab4661e8 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 GNU/Linux
```

**Comment by dznz** [comment]
Hmm, wait, that was mostly not useful. My brain is elsewhere. Gimme a minute

**Comment by dznz** [comment]
I'm gonna file the "No header found" thing independently I think.

**Comment by flaviusb** [comment]
Does this issue still seem to be the case eg is `args.len() == 2` when invoked as `cargo run examples/self.🍍🍕 --html`?
